name: "inspect-health-with-ssh-and-curl-action"
description: "Github action for inspecting service health for the service which doesn't expose HTTP/HTTPS. The SSH public authentication with the combination of health probe using actuator endpoint are leveraged."
author: "Win"
inputs:
  host:
    description: "SSHPASS host"
    required: true
  port:
    description: "SSHPASS host"
    default: 22
  username:
    description: "SSHPASS username"
    required: true
  module_port:
    description: "Module's internal port"
    required: true
  ssh_private_key:
    description: "private key to set up Public Key Authentication with SSH"
    required: true
outputs:
  status:
    description: "Status of service health. 0 indicates that service is up, 1 indicates the service unavailabilty"
runs:
  using: "docker"
  image: "Dockerfile"
  env:
    HOST: ${{ inputs.host }}
    PORT: ${{ inputs.port }}
    USERNAME: ${{ inputs.username }}
    SERVICE_PORT: ${{ inputs.module_port }}
    SSH_PRIVATE_KEY: ${{ inputs.ssh_private_key }}
