name: Test action

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Execute sshpass
        id: inspect-service-health
        uses: ./
        with:
          host: ${{ secrets.HOST}}
          username: ${{ secrets.USERNAME}}
          ssh_private_key: ${{ secrets.SSH_PRIVATE_KEY}}
          module_port: ${{ secrets.MODULE_PORT}}

      - name: Display service health
        run: echo "${{ steps.inspect-service-health.outputs.status }}"
